# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bb1d7cfb92819055c600c7db40289311d72b8c72626493a0ec849caf27b3d5f9cf7ae0338afeebcd7567e9ff0157225bc41acfccab8b89afcf4af1fb603aea0

test:
  secret_key_base: 269d037d78293213c8f4b3ee566700ef4d0ccadac64e129bde0863b386e7f926fc5ac63df4b777424bb7396d6b743079a1247e66de35e5f2728c701dc3b56611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 269d037d78293213c8f4b3ee566700ef4d0ccadac64e129bde0863b386e7f926fc5ac63df4b777424bb7396d6b743079a1247e66de35e5f2728c701dc3b566gg
